# Generated by Django 5.2.12 on 2026-04-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_support_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsupportmessage',
            name='feedback_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientsupportmessage',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='clientsupportmessage',
            name='support_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientsupportmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteenquiry',
            name='enquiry_status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='siteenquiry',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='siteenquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
