# Generated by Django 5.2.12 on 2026-04-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_client_support_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteenquiry',
            name='enquiry_kind',
            field=models.CharField(choices=[('general', 'General contact'), ('service', 'Service enquiry')], db_index=True, default='general', max_length=32),
        ),
        migrations.AddField(
            model_name='siteenquiry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='siteenquiry',
            name='service_topic',
            field=models.CharField(blank=True, default='', help_text='What service the visitor is asking about (home page service form).', max_length=255),
        ),
    ]
