# Generated by Django 5.2.12 on 2026-04-02 08:28

import re

from django.db import migrations, models


def _digits_10(raw):
    if not raw:
        return ""
    d = re.sub(r"\D", "", str(raw))
    if len(d) == 12 and d.startswith("91"):
        d = d[2:]
    if len(d) == 11 and d.startswith("0"):
        d = d[1:]
    return d if len(d) == 10 else ""


def normalize_site_enquiry_phones(apps, schema_editor):
    SiteEnquiry = apps.get_model("core", "SiteEnquiry")
    for row in SiteEnquiry.objects.all().only("id", "phone"):
        new_p = _digits_10(row.phone)
        if new_p != row.phone:
            row.phone = new_p
            row.save(update_fields=["phone"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_site_enquiry_service_fields'),
    ]

    operations = [
        migrations.RunPython(normalize_site_enquiry_phones, noop_reverse),
        migrations.AlterField(
            model_name='siteenquiry',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='10-digit mobile for service enquiries.', max_length=10),
        ),
    ]
