# Generated by Django 5.2.12 on 2026-04-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_feature_plan_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='feature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
