# Generated by Django 5.2.12 on 2026-04-02 07:27

from decimal import Decimal

from django.db import migrations, models


STARTER_FEATURES = [
    "Dynamic webpage",
    "5 default color themes — fully customisable",
    "WhatsApp integration",
    "Analytics on clients",
    "Upload up to 10 images",
    "Email notification on client enquiries",
    "Insights on end-user activity on your page",
]


def seed_starter_pro_plans_and_features(apps, schema_editor):
    Plan = apps.get_model("plans", "Plan")
    Feature = apps.get_model("plans", "Feature")
    active = "active"

    starter = Plan.objects.filter(name="Starter").first()
    if starter:
        starter.price = Decimal("499.00")
        starter.first_activation_price = Decimal("299.00")
        starter.coming_soon = False
        starter.save()
        Feature.objects.filter(plan=starter).delete()
        for name in STARTER_FEATURES:
            Feature.objects.create(plan=starter, name=name, record_status=active)

    pro = Plan.objects.filter(name="Pro").first()
    if pro:
        pro.price = Decimal("999.00")
        pro.first_activation_price = None
        pro.coming_soon = True
        pro.save()
        Feature.objects.filter(plan=pro).delete()
        Feature.objects.create(
            plan=pro, name="Coming soon", record_status=active
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_feature_record_status_feature_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='When true, plan is listed but not available for purchase yet.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='first_activation_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price for first-time website activation (e.g. Starter promo).', max_digits=10, null=True),
        ),
        migrations.RunPython(seed_starter_pro_plans_and_features, noop_reverse),
    ]
