# Generated by Django 5.2.12 on 2026-04-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_location_map_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crystallead',
            new_name='businesses__busines_d8443f_idx',
            old_name='crystallead_biz_type_created',
        ),
    ]
