# Generated by Django 5.2.12 on 2026-04-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_crystallead_record_status_crystallead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16),
        ),
    ]
