# Generated by Django 5.2.12 on 2026-04-02 08:28

import re

from django.db import migrations, models


def _digits_10(raw):
    if not raw:
        return ""
    d = re.sub(r"\D", "", str(raw))
    if len(d) == 12 and d.startswith("91"):
        d = d[2:]
    if len(d) == 11 and d.startswith("0"):
        d = d[1:]
    return d if len(d) == 10 else ""


def normalize_business_phones(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    for row in Business.objects.all().only("id", "phone"):
        if not row.phone:
            continue
        new_p = _digits_10(row.phone)
        if new_p != row.phone:
            row.phone = new_p
            row.save(update_fields=["phone"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_businessenquiry'),
    ]

    operations = [
        migrations.RunPython(normalize_business_phones, noop_reverse),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digit mobile number (no spaces or country code stored).', max_length=10),
        ),
    ]
