# Generated by Django 5.2.12 on 2026-04-02 12:24

from django.db import migrations, models


def set_dashboard_admin_roles(apps, schema_editor):
    Customer = apps.get_model("authentication", "Customer")
    Customer.objects.filter(email__iexact="crystal.gym.in@gmail.com").update(role=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customer_record_status_emailotp_record_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'client'), (2, 'client_customer')], db_index=True, default=1),
        ),
        migrations.RunPython(set_dashboard_admin_roles, noop_reverse),
    ]
